In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
file ='/content/drive/MyDrive/kindle_dataset/all_kindle_review.csv'

In [ ]:
df=pd.read_csv(file)

In [ ]:
df

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0                 0       11539  B0033UV8HI  [8, 10]       3   
1                 1        5957  B002HJV4DE   [1, 1]       5   
2                 2        9146  B002ZG96I4   [0, 0]       3   
3                 3        7038  B002QHWOEU   [1, 3]       3   
4                 4        1776  B001A06VJ8   [0, 1]       4   
...             ...         ...         ...      ...     ...   
11995         11995        2183  B001DUGORO   [0, 0]       4   
11996         11996        6272  B002JCSFSQ   [2, 2]       5   
11997         11997       12483  B0035N1V7K   [0, 1]       3   
11998         11998        3640  B001W1XT40   [1, 2]       1   
11999         11999       11398  B003370JUS   [5, 6]       3   

                                              reviewText   reviewTime  \
0      Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1      Great short read.  I didn't want to put it dow...   10 8, 2013   
2      I'll start by saying this is the first of four...  04 11, 2014   
3      Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4      I did not expect this type of book to be in li...  12 31, 2012   
...                                                  ...          ...   
11995  Valentine cupid is a vampire- Jena and Ian ano...  02 28, 2014   
11996  I have read all seven books in this series. Ap...  05 16, 2011   
11997  This book really just wasn't my cuppa.  The si...  07 26, 2013   
11998  tried to use it to charge my kindle, it didn't...  09 17, 2013   
11999  Taking Instruction is a look into the often hi...   07 5, 2012   

           reviewerID                   reviewerName  \
0      A3HHXRELK8BHQG                         Ridley   
1      A2RGNZ0TRF578I                   Holly Butler   
2      A3S0H2HV6U1I7F                        Merissa   
3       AC4OQW3GZ919J                     Cleargrace   
4      A3C9V987IQHOQD                       Rjostler   
...               ...                            ...   
11995  A1OKS5Q1HD8WQC                  lisa jon jung   
11996   AQRSPXLNEQAMA                        TerryLP   
11997  A2T5QLT5VXOJAK                        hwilson   
11998  A28MHD2DDY6DXB  Allison A. Slater "Gryphon50"   
11999  A3JUXLB4K9ZXCC                      Dafna Yee   

                                                 summary  unixReviewTime  
0                               Entertaining But Average      1283385600  
1                                Terrific menage scenes!      1381190400  
2                                       Snapdragon Alley      1397174400  
3                                 very light murder cozy      1404518400  
4                                                   Book      1356912000  
...                                                  ...             ...  
11995                                               jena      1393545600  
11996                                Peacekeepers Series      1305504000  
11997                                    a little creepy      1374796800  
11998                                        didn't work      1379376000  
11999  If you like BDSM with a touch of romance, this...      1341446400  

[12000 rows x 11 columns]

In [ ]:
df=df[['reviewText','rating']]

In [ ]:
df.shape

(12000, 2)

In [ ]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [ ]:
df.dropna(subset=['reviewText'],inplace=True)

/tmp/ipython-input-11-3955189854.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=['reviewText'],inplace=True)


In [ ]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [ ]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [ ]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [ ]:
#positive review 1 and negative 0
df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)

/tmp/ipython-input-11-668525254.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)


In [ ]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [ ]:
#1.lower all text
df['reviewText']=df['reviewText'].str.lower()

/tmp/ipython-input-13-174506692.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].str.lower()


In [ ]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
##remove special character
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+','',x))
##remove stopword
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
df['reviewText']=df['reviewText'].apply(lambda x:re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x:BeautifulSoup(x,'lxml').get_text())
##remove aditional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

/tmp/ipython-input-17-2642386102.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+','',x))
/tmp/ipython-input-17-2642386102.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
/tmp/ipython-input-17-2642386102.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try usin

In [ ]:
df.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
def lemmatize_words(text):
  return " ".join(lemmatizer.lemmatize(word) for word in text.split())

In [ ]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

/tmp/ipython-input-21-1959687590.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))


In [ ]:
df

reviewText  rating
0      jace rankin may short he nothing mess man haul...       1
1      great short read didnt want put read one sitti...       1
2      ill start saying first four book wasnt expecti...       1
3      aggie angela lansbury carry pocketbook instead...       1
4      expect type book library pleased find price right       1
...                                                  ...     ...
11995  valentine cupid vampire jena ian another vampi...       1
11996  read seven book series apocalypticadventure on...       1
11997  book really wasnt cuppa situation man capturin...       1
11998  tried use charge kindle didnt even register ch...       0
11999  taking instruction look often hidden world sex...       1

[12000 rows x 2 columns]

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],test_size=0.2,random_state=42)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()


In [ ]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
model_bow=GaussianNB()
model_bow.fit(X_train_bow,y_train)

model_tfidf=GaussianNB()
model_tfidf.fit(X_train_tfidf,y_train)

GaussianNB()

In [ ]:
y_pred_bow=model_bow.predict(X_test_bow)
y_pred_tfidf=model_tfidf.predict(X_test_tfidf)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("BOW")
print(accuracy_score(y_test,y_pred_bow))
print(confusion_matrix(y_test,y_pred_bow))
print(classification_report(y_test,y_pred_bow))
print(" ")
print("TFIDF")
print(accuracy_score(y_test,y_pred_tfidf))
print(confusion_matrix(y_test,y_pred_tfidf))
print(classification_report(y_test,y_pred_tfidf))

BOW
0.5775
[[499 304]
 [710 887]]
              precision    recall  f1-score   support

           0       0.41      0.62      0.50       803
           1       0.74      0.56      0.64      1597

    accuracy                           0.58      2400
   macro avg       0.58      0.59      0.57      2400
weighted avg       0.63      0.58      0.59      2400

 
TFIDF
0.57875
[[482 321]
 [690 907]]
              precision    recall  f1-score   support

           0       0.41      0.60      0.49       803
           1       0.74      0.57      0.64      1597

    accuracy                           0.58      2400
   macro avg       0.57      0.58      0.57      2400
weighted avg       0.63      0.58      0.59      2400



In [ ]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 86.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 114.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 16.2 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
thinc 8.3.6 re

In [ ]:
import gensim

In [ ]:
from gensim.models import Word2Vec,KeyedVectors

In [ ]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
vec_king=wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
vec_king.shape

(300,)

In [ ]:
from gensim.utils import simple_preprocess

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
words=[]
for i in range(len(df['reviewText'])):
  df['reviewText'][i]=simple_preprocess(df['reviewText'][i])
  words.append(df['reviewText'][i])

Streaming output truncated to the last 5000 lines.
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['reviewText'][i]=simple_preprocess(df['reviewText'][i])
/tmp/ipython-input-29-1391781404.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'][i]=simple_preprocess(df['reviewText'][i])
/tmp/ipython-input-29-1391781404.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values

In [ ]:
w2v_model=gensim.models.Word2Vec(words)

In [ ]:
w2v_model.wv.index_to_key

['book',
 'story',
 'read',
 'one',
 'character',
 'like',
 'good',
 'would',
 'really',
 'love',
 'time',
 'get',
 'author',
 'reading',
 'series',
 'much',
 'first',
 'well',
 'even',
 'didnt',
 'short',
 'know',
 'way',
 'could',
 'great',
 'make',
 'sex',
 'little',
 'dont',
 'thing',
 'want',
 'two',
 'think',
 'find',
 'plot',
 'also',
 'romance',
 'end',
 'life',
 'im',
 'see',
 'enjoyed',
 'go',
 'scene',
 'never',
 'take',
 'woman',
 'many',
 'lot',
 'written',
 'kindle',
 'say',
 'work',
 'thought',
 'bit',
 'found',
 'year',
 'going',
 'give',
 'interesting',
 'liked',
 'writing',
 'novel',
 'loved',
 'another',
 'feel',
 'better',
 'got',
 'come',
 'man',
 'hot',
 'still',
 'enough',
 'back',
 'though',
 'people',
 'reader',
 'made',
 'star',
 'review',
 'something',
 'part',
 'friend',
 'cant',
 'page',
 'need',
 'bad',
 'keep',
 'new',
 'wasnt',
 'free',
 'world',
 'doesnt',
 'relationship',
 'enjoy',
 'recommend',
 'together',
 'next',
 'start',
 'felt',
 'best',
 'put',

In [ ]:
#vocabularay size
w2v_model.corpus_count

12000

In [ ]:
import numpy as np

In [ ]:
def avg_word2vec(doc):
    vectors = [w2v_model.wv[word] for word in doc if word in w2v_model.wv.index_to_key]

    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(w2v_model.vector_size)

In [ ]:
!pip install tqdm

In [ ]:
from tqdm import tqdm

In [ ]:
X=[]
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

100%|██████████| 12000/12000 [00:20<00:00, 595.90it/s]


In [ ]:
X

[array([-2.6095632e-01,  3.2201463e-01,  1.6281256e-01,  1.2483516e-01,
         1.0841880e-01, -3.5899073e-01, -3.5330009e-02,  7.2271544e-01,
        -2.4419791e-01, -2.9572159e-01, -2.2081691e-01, -2.3585346e-01,
         6.6028431e-02, -5.4424774e-04,  1.1521957e-01, -3.0820736e-01,
         5.5498280e-02, -4.9454197e-01,  9.6820727e-02, -5.0141156e-01,
        -4.3773446e-02,  1.3456470e-01,  6.4642221e-02, -2.5756577e-01,
         2.5593702e-02, -1.2067639e-01, -3.2855874e-01, -6.2045073e-03,
        -3.0210248e-01,  2.1182980e-01,  3.6636919e-01, -1.3145004e-01,
         1.1484959e-01, -2.3224366e-01, -1.8524040e-02,  2.6741162e-01,
         3.3848707e-02, -1.9498324e-01, -1.8697605e-01, -6.5906936e-01,
        -1.5339878e-01, -2.1405156e-01, -2.1959297e-01, -1.3590436e-01,
         1.0673618e-01, -1.3525240e-01, -1.8172612e-02, -3.4068502e-02,
         1.6026752e-01,  2.3603493e-01,  1.7118150e-01, -2.8669792e-01,
        -3.5327323e-02,  3.3673510e-02, -2.5890747e-01,  1.33874

In [ ]:
len(X)

12000

In [ ]:
#independent feature
X_new=np.array(X)

In [ ]:
X_new.shape

(12000, 100)

In [ ]:
X_new[0].shape

(100,)

In [ ]:
#dependent feature
y=df['rating']

In [ ]:
y

0        1
1        1
2        1
3        1
4        1
        ..
11995    1
11996    1
11997    1
11998    0
11999    1
Name: rating, Length: 12000, dtype: int64

In [ ]:
y.shape

(12000,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("AVG word2vec")
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

AVG word2vec
0.7225
[[ 598  205]
 [ 461 1136]]
              precision    recall  f1-score   support

           0       0.56      0.74      0.64       803
           1       0.85      0.71      0.77      1597

    accuracy                           0.72      2400
   macro avg       0.71      0.73      0.71      2400
weighted avg       0.75      0.72      0.73      2400



In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Accuracy: 0.7816666666666666
[[ 450  353]
 [ 171 1426]]
              precision    recall  f1-score   support

           0       0.72      0.56      0.63       803
           1       0.80      0.89      0.84      1597

    accuracy                           0.78      2400
   macro avg       0.76      0.73      0.74      2400
weighted avg       0.78      0.78      0.77      2400



In [ ]:
import joblib
joblib.dump(model, 'logistic_model.pkl')


['logistic_model.pkl']

In [ ]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X_new, y)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42)

# Step 3: Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Step 4: Evaluate
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.77625
[[1300  305]
 [ 411 1184]]
              precision    recall  f1-score   support

           0       0.76      0.81      0.78      1605
           1       0.80      0.74      0.77      1595

    accuracy                           0.78      3200
   macro avg       0.78      0.78      0.78      3200
weighted avg       0.78      0.78      0.78      3200



In [ ]:
import joblib
joblib.dump(model, 'logistic_model_smote.pkl')


['logistic_model_smote.pkl']

In [ ]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# Split SMOTE-balanced data
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42)

# Initialize and train XGBoost classifier
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_model.fit(X_train, y_train)

# Predict
y_pred = xgb_model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:24:30] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Accuracy: 0.830625
[[1411  194]
 [ 348 1247]]
              precision    recall  f1-score   support

           0       0.80      0.88      0.84      1605
           1       0.87      0.78      0.82      1595

    accuracy                           0.83      3200
   macro avg       0.83      0.83      0.83      3200
weighted avg       0.83      0.83      0.83      3200



In [ ]:
import joblib
joblib.dump(xgb_model, 'xgboost_model_smote.pkl')


['xgboost_model_smote.pkl']

In [ ]:
w2v_model.save('word2vec_model.model')


In [ ]:
import joblib
import numpy as np
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')

# Load models
xgb_model = joblib.load('xgboost_model_smote.pkl')
w2v_model = Word2Vec.load('word2vec_model.model')

# Your avg_word2vec function
def avg_word2vec(doc, w2v_model):
    vectors = [w2v_model.wv[word] for word in doc if word in w2v_model.wv.key_to_index]
    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(w2v_model.vector_size)

# === TEST INPUT ===
text = "This book was truly inspiring and beautifully written!"

# Preprocess
tokens = word_tokenize(text.lower())
vector = avg_word2vec(tokens, w2v_model).reshape(1, -1)

# Predict
prediction = xgb_model.predict(vector)[0]
print("Prediction:", "Positive" if prediction == 1 else "Negative")


Prediction: Positive


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
texts = [
    "Terrible plot, I hated the book.",
    "Amazing storyline, I loved every chapter.",
    "It was okay, not too bad but not great.",
]

for t in texts:
    tokens = word_tokenize(t.lower())
    vector = avg_word2vec(tokens, w2v_model).reshape(1, -1)
    prediction = xgb_model.predict(vector)[0]
    print(f"{t} → {'Positive' if prediction == 1 else 'Negative'}")


Terrible plot, I hated the book. → Negative
Amazing storyline, I loved every chapter. → Positive
It was okay, not too bad but not great. → Negative
